spring:
  config:
    activate:
      on-profile: dev
      
  datasource:
    url: jdbc:postgresql://localhost:5442/userservicedb
    username: userservice
    password: userservice
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: update   # dev only; Flyway later
    properties:
      hibernate:
        format_sql: true
    show-sql: true

app:
  env: dev

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

# dev-only props can go here
server:
  port: 8080
